# https://dev.azure.com/home-assistant

trigger:
  tags:
    include:
    - '*'
pr: none

variables:
  - name: versionBuilder
    value: '6.4'
  - group: docker

jobs:

- job: 'Alpine'
  pool:
    vmImage: 'ubuntu-16.04'
  strategy:
    matrix:
      alpine38:
        buildVersion: '3.8'
        buildArch: '--amd64 --i386 --armhf --aarch64'
        buildArgs: '--no-latest'
      alpine39:
        buildVersion: '3.9'
        buildArch: '--all'
        buildArgs: '--no-latest'
      alpine310:
        buildVersion: '3.10'
        buildArch: '--all'
        buildArgs: '--no-latest'
      alpine311:
        buildVersion: '3.11'
        buildArch: '--all'
        buildArgs: ''
  steps:
  - script: sudo docker login -u $(dockerUser) -p $(dockerPassword)
    displayName: 'Docker hub login'
  - script: sudo docker pull homeassistant/amd64-builder:$(versionBuilder)
    displayName: 'Install Builder'
  - script: |
      sudo docker run --rm --privileged \
        -v ~/.docker:/root/.docker \
        -v /run/docker.sock:/run/docker.sock:rw -v $(pwd):/data:ro \
        homeassistant/amd64-builder:$(versionBuilder) --base $(buildVersion) \
        $(buildArch) -t /data/alpine --docker-hub homeassistant \
        $(buildArgs) --release $(Build.SourceBranchName)
    displayName: 'Build Alpine base-images'


- template: .azure/azp-template-python.yml
  parameters:
    name: '36_Alpine310'
    version: '3.6=3.10'
    args: '--no-latest'


- template: .azure/azp-template-python.yml
  parameters:
    name: '36_Alpine311'
    version: '3.6=3.11'
    args: '--no-latest --release-tag'


- template: .azure/azp-template-python.yml
  parameters:
    name: '37_Alpine310'
    version: '3.7=3.10'
    args: '--no-latest'


- template: .azure/azp-template-python.yml
  parameters:
    name: '37_Alpine311'
    version: '3.7=3.11'
    args: '--release-tag --no-latest'


- template: .azure/azp-template-python.yml
  parameters:
    name: '38_Alpine310'
    version: '3.8=3.10'
    args: '--no-latest'


- template: .azure/azp-template-python.yml
  parameters:
    name: '38_Alpine311'
    version: '3.8=3.11'
    args: '--release-tag'


- job: 'Ubuntu'
  pool:
    vmImage: 'ubuntu-16.04'
  strategy:
    matrix:
      trusty:
        buildVersion: '14.04'
        buildArch: '--amd64 --i386 --armv7 --aarch64'
        buildLatest: '--no-latest'
      xenial:
        buildVersion: '16.04'
        buildArch: '--amd64 --i386 --armv7 --aarch64'
        buildLatest: '--no-latest'
      bionic:
        buildVersion: '18.04'
        buildArch: '--amd64 --i386 --armv7 --aarch64'
        buildLatest: ''
      focal:
        buildVersion: '20.04'
        buildArch: '--amd64 --armv7 --aarch64'
        buildLatest: '--no-latest'
  steps:
  - script: sudo docker login -u $(dockerUser) -p $(dockerPassword)
    displayName: 'Docker hub login'
  - script: sudo docker pull homeassistant/amd64-builder:$(versionBuilder)
    displayName: 'Install Builder'
  - script: |
      sudo docker run --rm --privileged \
        -v ~/.docker:/root/.docker \
        -v /run/docker.sock:/run/docker.sock:rw -v $(pwd):/data:ro \
        homeassistant/amd64-builder:$(versionBuilder) \
        --base-ubuntu $(buildVersion) $(buildArch) \
        -t /data/ubuntu --docker-hub homeassistant $(buildLatest) \
        --release $(Build.SourceBranchName)
    displayName: 'Build Ubuntu base-images'


- job: 'Raspbian'
  pool:
    vmImage: 'ubuntu-16.04'
  strategy:
    matrix:
      jessie:
        buildVersion: 'jessie'
        buildLatest: '--no-latest'
      stretch:
        buildVersion: 'stretch'
        buildLatest: '--no-latest'
      buster:
        buildVersion: 'buster'
        buildLatest: ''
  steps:
  - script: sudo docker login -u $(dockerUser) -p $(dockerPassword)
    displayName: 'Docker hub login'
  - script: sudo docker pull homeassistant/amd64-builder:$(versionBuilder)
    displayName: 'Install Builder'
  - script: |
      sudo docker run --rm --privileged \
        -v ~/.docker:/root/.docker \
        -v /run/docker.sock:/run/docker.sock:rw -v $(pwd):/data:ro \
        homeassistant/amd64-builder:$(versionBuilder) \
        --base-raspbian $(buildVersion) --armhf \
        -t /data/raspbian --docker-hub homeassistant $(buildLatest) \
        --release $(Build.SourceBranchName)
    displayName: 'Build Ubuntu base-images'


- job: 'Debian'
  pool:
    vmImage: 'ubuntu-16.04'
  strategy:
    matrix:
      stretch:
        buildVersion: 'stretch'
        buildArch: '--amd64 --i386 --armv7 --armhf --aarch64'
        buildLatest: '--no-latest'
      buster:
        buildVersion: 'buster'
        buildArch: '--amd64 --i386 --armv7 --armhf --aarch64'
        buildLatest: ''
      bullseye:
        buildVersion: 'bullseye'
        buildArch: '--amd64 --i386 --armv7 --armhf --aarch64'
        buildLatest: '--no-latest'
  steps:
  - script: sudo docker login -u $(dockerUser) -p $(dockerPassword)
    displayName: 'Docker hub login'
  - script: sudo docker pull homeassistant/amd64-builder:$(versionBuilder)
    displayName: 'Install Builder'
  - script: |
      sudo docker run --rm --privileged \
        -v ~/.docker:/root/.docker \
        -v /run/docker.sock:/run/docker.sock:rw -v $(pwd):/data:ro \
        homeassistant/amd64-builder:$(versionBuilder) \
        --base-debian $(buildVersion) $(buildArch) \
        -t /data/debian --docker-hub homeassistant $(buildLatest) \
        --release $(Build.SourceBranchName)
    displayName: 'Build Ubuntu base-images'
